Checking out fb.py from git+git://github.com/emre/fb.py.git#egg=fb.py checkout from git+git://github.com/emre/fb.py.git#egg=fb.py
  Running command git config remote.origin.url
  git://github.com/emre/fb.py.git
  Clone in /home/emre/virtualenv/src/fb.py exists, and has correct URL (git://github.com/emre/fb.py.git)
  Updating clone /home/emre/virtualenv/src/fb.py
  Running command git fetch -q
  Running command git checkout -q -f master
  Running setup.py egg_info for package fb.py
    Traceback (most recent call last):
      File "<string>", line 13, in <module>
    IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 13, in <module>

IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1742, in install_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1346, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1
------------------------------------------------------------
/usr/lib/python2.6/dist-packages/pip.py run on Fri Aug 20 16:15:30 2010
Checking out fb.py from git+git://github.com/emre/fb.py.git#egg=fb.py checkout from git+git://github.com/emre/fb.py.git#egg=fb.py
  Running command git config remote.origin.url
  git://github.com/emre/fb.py.git
  Clone in /home/emre/virtualenv/src/fb.py exists, and has correct URL (git://github.com/emre/fb.py.git)
  Updating clone /home/emre/virtualenv/src/fb.py
  Running command git fetch -q
  Running command git checkout -q -f master
  Running setup.py egg_info for package fb.py
    Traceback (most recent call last):
      File "<string>", line 13, in <module>
    IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 13, in <module>

IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1742, in install_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1346, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1
------------------------------------------------------------
/usr/lib/python2.6/dist-packages/pip.py run on Fri Aug 20 16:16:31 2010
Checking out fb.py from git+git://github.com/egnity/fb.py.git#egg=fb.py checkout from git+git://github.com/egnity/fb.py.git#egg=fb.py
  Running command git config remote.origin.url
  git://github.com/emre/fb.py.git
  Git clone in /home/emre/virtualenv/src/fb.py exists with URL git://github.com/emre/fb.py.git
  The plan is to install the Git repository git://github.com/egnity/fb.py.git
  Running setup.py egg_info for package fb.py
    Traceback (most recent call last):
      File "<string>", line 13, in <module>
    IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 13, in <module>

IOError: [Errno 2] No such file or directory: '/home/emre/virtualenv/src/fb.py/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1742, in install_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1346, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1
------------------------------------------------------------
/usr/bin/pip run on Fri Aug 20 16:29:14 2010
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 404, in run
    InstallRequirement.from_editable(name))
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1207, in from_editable
    return cls(name, comes_from, source_dir=source_dir, editable=True, url=url)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1185, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2531, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2456, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2424, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'fb.py/src', 'at', '/src')
------------------------------------------------------------
/usr/bin/pip run on Fri Aug 20 16:30:19 2010
Checking out fbpy from git+git://github.com/egnity/fb.py.git#egg=fbpy checkout from git+git://github.com/egnity/fb.py.git#egg=fbpy
  Cloning git://github.com/egnity/fb.py.git to ./src/fbpy
  Running command git clone -q git://github.com/egnity/fb.py.git /home/emre/github/fb.py/src/fbpy
  Complete output from command git clone -q git://github.com/egnity/fb.py.git /home/emre/github/fb.py/src/fbpy:
  
----------------------------------------
Command git clone -q git://github.com/egnity/fb.py.git /home/emre/github/fb.py/src/fbpy failed with error code 128
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1741, in install_files
    req_to_install.update_editable()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1486, in update_editable
    version_control(self.url).obtain(self.source_dir)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 2804, in obtain
    [GIT_CMD, 'clone', '-q', url, dest])
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command git clone -q git://github.com/egnity/fb.py.git /home/emre/github/fb.py/src/fbpy failed with error code 128
------------------------------------------------------------
/usr/bin/pip run on Fri Aug 20 16:30:24 2010
Checking out fbpy from git+git://github.com/egnity/fb.py.git#egg=fbpy checkout from git+git://github.com/egnity/fb.py.git#egg=fbpy
  Cloning git://github.com/egnity/fb.py.git to ./src/fbpy
  Running command git clone -q git://github.com/egnity/fb.py.git /home/emre/github/fb.py/src/fbpy
  Complete output from command git clone -q git://github.com/egnity/fb.py.git /home/emre/github/fb.py/src/fbpy:
  
----------------------------------------
Command git clone -q git://github.com/egnity/fb.py.git /home/emre/github/fb.py/src/fbpy failed with error code 128
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 408, in run
    requirement_set.install_files(finder, force_root_egg_info=self.bundle)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1741, in install_files
    req_to_install.update_editable()
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1486, in update_editable
    version_control(self.url).obtain(self.source_dir)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 2804, in obtain
    [GIT_CMD, 'clone', '-q', url, dest])
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3543, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command git clone -q git://github.com/egnity/fb.py.git /home/emre/github/fb.py/src/fbpy failed with error code 128
------------------------------------------------------------
/usr/bin/pip run on Fri Aug 20 16:30:31 2010
--editable=git://github.com/egnity/fb.py.git is not the right format; it must have #egg=Package
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/pip.py", line 252, in main
    self.run(options, args)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 404, in run
    InstallRequirement.from_editable(name))
  File "/usr/lib/python2.6/dist-packages/pip.py", line 1202, in from_editable
    name, url = parse_editable(editable_req)
  File "/usr/lib/python2.6/dist-packages/pip.py", line 3674, in parse_editable
    % editable_req)
InstallationError: --editable=git://github.com/egnity/fb.py.git is not the right format; it must have #egg=Package
